name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  LLVM-MINGW-TOOLCHAIN-NAME: llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64
  PROJECT_NAME: dddw

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] # ubuntu latest is only used for building the windows aarch64 binary
        include:
          - os: ubuntu-latest
            toolchain: nightly
            target: aarch64-pc-windows-gnullvm
            name: Windows aarch64 (cross-compiled on Ubuntu 24.04)
            fid: aarch64-windows.exe
          - os: windows-latest
            toolchain: nightly
            target: x86_64-pc-windows-msvc
            name: Windows x86_64 (MSVC)
            fid: x86_64-windows.exe
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        target: ${{ matrix.target }}
        components: clippy
        default: true

    - name: Install LLVM MinGW toolchain (Windows aarch64)
      if: matrix.os == 'ubuntu-latest'
      run: |
          curl -L -o ${{ env.LLVM-MINGW-TOOLCHAIN-NAME }}.tar.xz https://github.com/mstorsjo/llvm-mingw/releases/download/20240619/${{ env.LLVM-MINGW-TOOLCHAIN-NAME }}.tar.xz
          tar -xf ${{ env.LLVM-MINGW-TOOLCHAIN-NAME }}.tar.xz
          echo "$GITHUB_WORKSPACE/${{ env.LLVM-MINGW-TOOLCHAIN-NAME }}/bin" >> $GITHUB_PATH
    
    - name: Build ${{ matrix.target }}
      run: cargo build --release --target ${{ matrix.target }}

    - name: Create release directory
      run: mkdir -p release

    - name: Move executable (Windows)
      if: matrix.os == 'windows-latest'
      run: mv target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}.exe release/${{ env.PROJECT_NAME }}-${{ matrix.fid }}

    - name: Move executable (Windows aarch64)
      if: matrix.os == 'ubuntu-latest'
      run: mv target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}.exe release/${{ env.PROJECT_NAME }}-${{ matrix.fid }}
    
    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }}-${{ matrix.fid }}
        path: release
    
  release:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - name: Download Windows binaries
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-x86_64-windows.exe
        path: ./release
    - name: Download Windows aarch64 binaries
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-aarch64-windows.exe
        path: ./release
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/${{ env.PROJECT_NAME }}-x86_64-windows.exe
          release/${{ env.PROJECT_NAME }}-aarch64-windows.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}